#!/usr/bin/env python3
"""
PackMule
    packmule

    Written By:
        Shane Hutter

    Description:
        A Python3 based wrapper and package manager for RHEL based Linux distributions.

    License:
        GNU GPLv3
"""

from PackMule        import (
        STATUS  ,
        )
from PackMule.args  import argparser

from sys            import exit
from traceback      import print_tb



def main( **argparser ):
    """
        Main code block
    """
    return exit(
            STATUS[ "success" ]
            )



if __main__ == '__name__':
    """
        Start main
    """
    try:
        main(
                argparser()
                )
    except Exception as error:
        print_tp()
        # log( error, log="fd2" )   # fd2 is a Stream log
        exit(
                STATUS[ "error" ]
                )
