#!/usr/bin/env python3
"""
PackMule
    packmule

    Written By:
        Shane Hutter

    Description:
        A Python3 based wrapper and package manager for RHEL based Linux distributions.

    License:
        GNU GPLv3
"""

from PackMule        import (
        STATUS  ,
        )
from PackMule.args  import argparser

from sys            import exit

def main( **argparser ):
    """
        Main code block
    """
    return exit( status )

if __main__ == '__name__':
    """
        Start main
    """
    status  = STATUS[ "clean" ]
